### ISSUE TITLE
Turtle Mob conflicts with Existing Mod: Turtle

### ISSUE THREAD

**Issue by Routhinator** [blert2112/water_mobs#1]
There was a pre-existing mod called Turtle for programmable turtle robots.

https://github.com/Novatux/turtle

The turtle mob in this pack will not load as it conflicts. Perhaps the mobs could be prefixed with mob_ or water_ to prevent such conflicts?

**Comment by blert2112** [comment]
I'm on vacation up in the mountains right now without my laptop or a reliable net connection. I will fix next weekend.

- Chris

**Comment by blert2112** [comment]
All fixed. Name changes all around for consistency. See the new repos... mobs_water and mobs_sky.
https://github.com/blert2112/mobs_water.git
https://github.com/blert2112/mobs_sky.git
